version: "3.9"
services:
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGO_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGO_PASSWORD
      - ME_CONFIG_MONGODB_URL=mongodb://$MONGO_USER:$MONGO_PASSWORD@mongo:27017/
    depends_on:
      - mongo
